# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest
container: maven:3.8.1-openjdk-17-slim
variables:
  - name: JAVA_HOME_11_X64
    value: /usr/local/openjdk-17
steps:
  - template: steps-prepare-maven.yml

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-DskipTests'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
    AppName: 'user-service'
    UseStagingDeployment: false
    DeploymentName: 'default'
    Package: '$(System.DefaultWorkingDirectory)/**/user-service/**/*.jar'

- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
    AppName: 'collection-service'
    UseStagingDeployment: false
    DeploymentName: 'default'
    Package: '$(System.DefaultWorkingDirectory)/**/collection-service/**/*.jar'

- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
    AppName: 'link-service'
    UseStagingDeployment: false
    DeploymentName: 'default'
    Package: '$(System.DefaultWorkingDirectory)/**/link-service/**/*.jar'

- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
    AppName: 'cloud-gateway'
    UseStagingDeployment: false
    DeploymentName: 'default'
    Package: '$(System.DefaultWorkingDirectory)/**/cloud-gateway/**/*.jar'


