jobs:
  - job: 1
    pool:
      vmImage: ubuntu-latest
    container: maven:3.8.1-openjdk-17-slim
    variables:
      - name: JAVA_HOME_11_X64
        value: /usr/local/openjdk-17
    steps:
      - template: steps-prepare-maven.yml
      - task: Maven@3
        displayName: 'java install' 
        inputs:
          mavenPomFile: pom.xml
          mavenOptions: -Xmx3072m $(MavenOpts)
          javaHomeSelection: 'path'
          jdkDirectory: '/usr/local/openjdk-17'
          publishJUnitResults: true
          testResultsFiles: "**/surefire-reports/TEST-*.xml"
          effectivePomSkip: true
          goals: -P production -pl ${{ parameters.moduleName }} -am $(MavenOpts) -Dmaven.test.skip=${{ parameters.skipTests }} $(BuildGoal)

      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          options: '-DskipTests'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

      - task: AzureSpringCloud@0
        inputs:
          azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
          Action: 'Deploy'
          AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
          AppName: 'user-service'
          UseStagingDeployment: true
          Package: '$(System.DefaultWorkingDirectory)/**/user-service/**/*.jar'

      - task: AzureSpringCloud@0
        inputs:
          azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
          Action: 'Deploy'
          AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
          AppName: 'collection-service'
          UseStagingDeployment: true
          Package: '$(System.DefaultWorkingDirectory)/**/collection-service/**/*.jar'

      - task: AzureSpringCloud@0
        inputs:
          azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
          Action: 'Deploy'
          AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
          AppName: 'link-service'
          UseStagingDeployment: true
          Package: '$(System.DefaultWorkingDirectory)/**/link-service/**/*.jar'

      - task: AzureSpringCloud@0
        inputs:
          azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
          Action: 'Deploy'
          AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
          AppName: 'cloud-gateway'
          UseStagingDeployment: true
          Package: '$(System.DefaultWorkingDirectory)/**/cloud-gateway/**/*.jar'