# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@3
  displayName: 'mavenbuild'
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-DskipTests'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: AzureSpringCloud@0
  displayName: 'cloudgateway'
  inputs:
    azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
    AppName: 'cloud-gateway'
    UseStagingDeployment: false
    DeploymentName: 'default'
    Package: '$(System.DefaultWorkingDirectory)/**/cloud-gateway/**/*.jar'

- task: AzureSpringCloud@0
  displayName: 'userservice'
  inputs:
    azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
    AppName: 'user-service'
    UseStagingDeployment: false
    DeploymentName: 'default'
    Package: '$(System.DefaultWorkingDirectory)/**/user-service/**/*.jar'

- task: AzureSpringCloud@0
  displayName: 'collectionservice'
  inputs:
    azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
    AppName: 'collection-service'
    UseStagingDeployment: false
    DeploymentName: 'default'
    Package: '$(System.DefaultWorkingDirectory)/**/collection-service/**/*.jar'

- task: AzureSpringCloud@0
  displayName: 'linkservice'
  inputs:
    azureSubscription: 'Free Trial(0a2e0152-0d3f-4878-b925-014f650a7cb7)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/0a2e0152-0d3f-4878-b925-014f650a7cb7/resourceGroups/spring_cloud/providers/Microsoft.AppPlatform/Spring/azure-dev-hackathon'
    AppName: 'link-service'
    UseStagingDeployment: false
    DeploymentName: 'default'
    Package: '$(System.DefaultWorkingDirectory)/**/link-service/**/*.jar'

